[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 10, y = 10 }

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "DejaVuSansM Nerd Font Mono" }
bold = { style = "medium" }
size = 15
offset.y = 5
