[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 2, y = 2 }

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "FiraCode Nerd Font", style = "Light" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic =  { family = "FiraCode Nerd Font", style = "Italic" }
size = 15
offset.y = 1
offset.x = 1
