[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "SF Mono", style = "Regular" }
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
# normal = { family = "Monaco" }
# bold = { style = "bold" }
size = 15
offset.y = 3
