[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Thin" }
# bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
# italic =  { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
# normal = { family = "SF Mono", style = "Light" }
# bold = { family = "SF Mono", style = "Bold" }
# italic =  { family = "SF Mono", style = "Italic" }
# normal = { family = "Berkeley Mono", style = "Regular" }
# bold = { family = "Berkeley Mono", style = "Bold" }
# italic = { family = "Berkeley Mono", style = "Italic" }
normal = { family = "MesloLGM Nerd Font Mono" }
italic = { style = "italic" }
bold = { style = "bold" }
size = 13
offset.y = 0

# Dracula

# [colors.primary]
# background = "0x282a36"
# foreground = "0xf8f8f2"

# [colors.normal]
# black = "0x21222c"
# red = "0xff5555"
# green = "0x50fa7b"
# yellow = "0xf1fa8c"
# blue = "0xbd93f9"
# magenta = "0xff79c6"
# cyan = "0x8be9fd"
# white = "0xf8f8f2"

# [colors.bright]
# black = "0x6272a4"
# red = "0xff6e6e"
# green = "0x69ff94"
# yellow = "0xffffa5"
# blue = "0xd6acff"
# magenta = "0xff92df"
# cyan = "0xa4ffff"
# white = "0xffffff"

# Light

# [colors.primary]
# background = "0xffffff"
# foreground = "0x000000"

# [colors.normal]
# black = "0x000000"
# red = "0xcd0000"
# green = "0x00cd00"
# yellow = "0xcdcd00"
# blue = "0x0000ee"
# magenta = "0xcd00cd"
# cyan = "0x00cdcd"
# white = "0xe5e5e5"

# [colors.bright]
# black = "0x7f7f7f"
# red = "0xff0000"
# green = "0x00ff00"
# yellow = "0xffff00"
# blue = "0x5c5cff"
# magenta = "0xff00ff"
# cyan = "0x00ffff"
# white = "0xffffff"
