[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 10, y = 10 }

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "FiraCode Nerd Font Mono", style = "Light" }
normal = { family = "Monaco" }
bold = { style = "bold" }
size = 13
offset.y = 0

# Colors (LuciusBlackLowContrast)
[colors.primary]
    background =  '#121212'
    foreground =  '#bcbcbc'

# Cursor colors
[colors.cursor]
    text= '#121212'
    cursor= '#5f87af'

  # Selection colors
  [colors.selection]
    text= '#bcbcbc'
    background= '#005f87'

  # Normal colors
  [colors.normal]
    black=   '#121212'
    red=     '#d75f5f'
    green=   '#87af5f'
    yellow=  '#afaf87'
    blue=    '#5fafd7'
    magenta= '#af87af'
    cyan=    '#5faf87'
    white=   '#bcbcbc'

  # Bright colors
  [colors.bright]
    black=   '#121212'
    red=     '#d75f5f'
    green=   '#87af5f'
    yellow=  '#afaf87'
    blue=    '#5fafd7'
    magenta= '#af87af'
    cyan=    '#5faf87'
    white=   '#bcbcbc'
