[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "SF Mono", style = "Light" }
# bold = { family = "SF Mono", style = "Bold" }
# italic =  { family = "SF Mono", style = "Italic" }
# normal = { family = "Berkeley Mono", style = "Regular" }
# bold = { family = "Berkeley Mono", style = "Bold" }
# italic = { family = "Berkeley Mono", style = "Italic" }
normal = { family = "Menlo" }
bold = { style = "bold" }
size = 15
offset.y = 10

# [colors.primary]
# background = "0xffffff"
# foreground = "0x000000"

# [colors.normal]
# black = "0x000000"
# red = "0xcd0000"
# green = "0x00cd00"
# yellow = "0xcdcd00"
# blue = "0x0000ee"
# magenta = "0xcd00cd"
# cyan = "0x00cdcd"
# white = "0xe5e5e5"

# [colors.bright]
# black = "0x7f7f7f"
# red = "0xff0000"
# green = "0x00ff00"
# yellow = "0xffff00"
# blue = "0x5c5cff"
# magenta = "0xff00ff"
# cyan = "0x00ffff"
# white = "0xffffff"
