[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic =  { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
# normal = { family = "SFMono Nerd Font", style = "Light" }
# bold = { family = "SFMono Nerd Font", style = "Bold" }
# italic =  { family = "SFMono Nerd Font", style = "Italic" }
# normal = { family = "Berkeley Mono", style = "Regular" }
# bold = { family = "Berkeley Mono", style = "Bold" }
# italic = { family = "Berkeley Mono", style = "Italic" }
normal = { family = "Monaco Nerd Font Mono" }
italic = { style = "italic" }
bold = { style = "bold" }
size = 13
offset.y = 3

# Colors (Solarized Dark)

# Default colors
[colors.primary]
background = '#002b36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'



## TokyoNight Alacritty Colors
## Default colors
#[colors.primary]
#background = '#222436'
#foreground = '#c8d3f5'

##[colors.cursor]
##cursor = '#c8d3f5'
##text = '#222436'

## Normal colors
#[colors.normal]
#black = '#1b1d2b'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#828bb8'

## Bright colors
#[colors.bright]
#black = '#444a73'
#red = '#ff757f'
#green = '#c3e88d'
#yellow = '#ffc777'
#blue = '#82aaff'
#magenta = '#c099ff'
#cyan = '#86e1fc'
#white = '#c8d3f5'

## Indexed Colors
#[[colors.indexed_colors]]
#index = 16
#color = '#ff966c'

#[[colors.indexed_colors]]
#index = 17
#color = '#c53b53'

# Dracula

# [colors.primary]
# background = "0x282a36"
# foreground = "0xf8f8f2"

# [colors.normal]
# black = "0x21222c"
# red = "0xff5555"
# green = "0x50fa7b"
# yellow = "0xf1fa8c"
# blue = "0xbd93f9"
# magenta = "0xff79c6"
# cyan = "0x8be9fd"
# white = "0xf8f8f2"

# [colors.bright]
# black = "0x6272a4"
# red = "0xff6e6e"
# green = "0x69ff94"
# yellow = "0xffffa5"
# blue = "0xd6acff"
# magenta = "0xff92df"
# cyan = "0xa4ffff"
# white = "0xffffff"

# Light

# [colors.primary]
# background = "0xffffff"
# foreground = "0x000000"

# [colors.normal]
# black = "0x000000"
# red = "0xcd0000"
# green = "0x00cd00"
# yellow = "0xcdcd00"
# blue = "0x0000ee"
# magenta = "0xcd00cd"
# cyan = "0x00cdcd"
# white = "0xe5e5e5"

# [colors.bright]
# black = "0x7f7f7f"
# red = "0xff0000"
# green = "0x00ff00"
# yellow = "0xffff00"
# blue = "0x5c5cff"
# magenta = "0xff00ff"
# cyan = "0x00ffff"
# white = "0xffffff"
