[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding = { x = 0, y = 0 }

[scrolling]
history = 100000
multiplier = 5

[font]
# normal = { family = "JetBrainsMono Nerd Font" }
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
# italic =  { family = "JetBrainsMono Nerd Font", style = "Italic" }
# normal = { family = "SFMono Nerd Font", style = "Light" }
# bold = { family = "SFMono Nerd Font", style = "Bold" }
# italic =  { family = "SFMono Nerd Font", style = "Italic" }
# normal = { family = "Berkeley Mono", style = "Regular" }
# bold = { family = "Berkeley Mono", style = "Bold" }
# italic = { family = "Berkeley Mono", style = "Italic" }
normal = { family = "Menlo" }
italic = { style = "italic" }
bold = { style = "bold" }
size = 15
offset.y = 3
